"""Render the checked local NIETS papers into inline question images.

Run from the repository root. Source PDFs are in tmp/onet; only the WebP
question crops and their dimensions are deployed. Crops retain original
wording, diagrams, option order, and watermarks.
"""
import json
import re
from pathlib import Path

import pymupdf as fitz
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'assets/exercises/onet-images'
OUT.mkdir(parents=True, exist_ok=True)
rows = re.findall(r'\[(25\d\d),(\d+),(\d+),', (ROOT / 'assets/exercises/onet-originals.js').read_text(encoding='utf-8'))

# Fractions of the source page, manually checked against the rendered papers.
# Multiple questions on one page must not leak into the adjacent crop.
ranges = {
    '2568-4': (.21,.38), '2568-5': (.395,.862),
    '2568-6': (.21,.43), '2568-7': (.445,.67),
    '2568-10': (.21,.645), '2568-11': (.665,.84),
    '2568-13': (.21,.49), '2568-14': (.505,.72),
    '2568-19': (.21,.49), '2568-20': (.505,.80),
    '2568-24': (.21,.49), '2568-25': (.505,.78),
    '2568-26': (.21,.43), '2568-31': (.21,.40), '2568-32': (.42,.72),
    '2567-1': (.30,.92), '2567-4': (.16,.38), '2567-5': (.405,.945),
    '2566-1': (.285,.84), '2566-2': (.155,.62), '2566-3': (.645,.94),
    '2566-5': (.655,.84), '2566-6': (.155,.38), '2566-7': (.405,.93),
    '2566-22': (.155,.405), '2566-23': (.44,.67), '2566-26': (.155,.59),
    '2566-25': (.155,.63),
    '2565-1': (.305,.61), '2565-2': (.155,.67), '2565-3': (.155,.66),
    '2564-6': (.16,.34), '2564-7': (.36,.63),
    '2563-1': (.33,.90), '2563-2': (.155,.81), '2563-3': (.155,.89), '2563-4': (.155,.76),
    '2562-3': (.155,.84), '2562-4': (.18,.63), '2562-6': (.155,.825),
    '2561-3': (.155,.565), '2561-4': (.155,.91), '2561-5': (.175,.912),
    '2560-4': (.39,.89),
    '2559-4': (.23,.56), '2559-5': (.575,.77),
}
documents = {}
manifest = {}
for year, number, page in rows:
    key = f'{year}-{number}'
    if year not in documents:
        documents[year] = fitz.open(ROOT / f'tmp/onet/{year}.pdf')
    source = documents[year][int(page)-1]
    if year == '2568':
        left, right, default = .13,.93,(.21,.862)
    elif year == '2559':
        left, right, default = .155,.91,(.23,.84)
    else:
        left, right, default = .045,.97,(.155,.94)
    top, bottom = ranges.get(key, default)
    bounds = source.rect
    clip = fitz.Rect(bounds.width*left,bounds.height*top,bounds.width*right,bounds.height*bottom)
    pix = source.get_pixmap(matrix=fitz.Matrix(2.4,2.4),clip=clip,alpha=False)
    img = Image.frombytes('RGB',(pix.width,pix.height),pix.samples)
    # Trim only empty top/bottom space. Dark ink establishes the content bounds;
    # original color and faint marks are preserved in the delivered image.
    ink = img.convert('L').point(lambda p: 255 if p < 115 else 0)
    box = ink.getbbox()
    if box:
        img = img.crop((0,max(0,box[1]-16),img.width,min(img.height,box[3]+16)))
    img.save(OUT / f'{key}.webp','WEBP',quality=90,method=6)
    manifest[key] = {'src':f'assets/exercises/onet-images/{key}.webp','width':img.width,'height':img.height}

(ROOT / 'assets/exercises/onet-images.js').write_text(
    '// Generated by scripts/render-onet-images.py from local official papers.\n'
    'window.SLH_ONET_IMAGES = '+json.dumps(manifest,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
print(f'Rendered {len(manifest)} question images; {sum(p.stat().st_size for p in OUT.glob("*.webp"))/1024/1024:.1f} MiB')
